version: <docker-compose-version>
services:
  database:
    image: <database-docker-image-name>
    ports:
      - "<databasePort>:<databasePort>"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

      POSTGRES_DB:
  <service-name>:
    image: <database-docker-image-name>
    ports:
      - "<databasePort>:<databasePort>"
    environment:
      PROFILE:
      DATABASESERVER_PORT:
    container_name: <container_name>
      networks:
      backend:
      aliases:
        - "alias"

    networks:
      backend:
    driver: bridge

